### ISSUE TITLE
Can't fit into terminal

### ISSUE THREAD

**Issue by jcubic** [patmooney/node-terminal-art#1]
I have standard 80 chars terminal emulator and image 100x100

```
const terminalArt = require('terminal-art');
console.log(process.argv[2]);
terminalArt.print(
    process.argv[2],
    {
     	output: 'log',
        maxCharWidth: +process.argv[3] || 80
    }
);
```
this `node ta.js 01.jpg 80` git image on terminal that is half the size of the screen and this `node ta.js 01.jpg 100` give image bigger then the terminal, there are only two modes, changing 80 to 90 take no effect, until the size match the input image size.

**Comment by patmooney** [comment]
Hi @jcubic Could you test with the new 1.2.3 version?

https://github.com/patmooney/node-terminal-art/commit/7ee615ccea71a52da9cef859ea46c8db34584708
