### ISSUE TITLE
Output Image errors

### ISSUE THREAD

**Issue by jcubic** [patmooney/node-terminal-art#2]
![ansi01](https://user-images.githubusercontent.com/280241/70787907-071c1b00-1d90-11ea-9907-9fed0cb4c247.png)

![01](https://user-images.githubusercontent.com/280241/70787920-0e432900-1d90-11ea-86a2-1ef77d47bc3b.jpg)

There are differences, it seems that only part of the ansi art in top right corner is correct. (XFce Fedora default terminal emulator).

My ANSI Art libray give similar output
https://codepen.io/jcubic/full/abzNaap
type `img https://placekitten.com/100/100`

**Comment by patmooney** [comment]
It might be that for the specific place it did it's sampling - grey was the closest colour. 
If I disable greys from the palette then we get something that looks like ->

![image](https://user-images.githubusercontent.com/1128374/81311043-cb565a80-907c-11ea-9a99-de6ec636436a.png)

Zoomed in...

![image](https://user-images.githubusercontent.com/1128374/81310719-63077900-907c-11ea-9a64-e94b82e6aeed.png)

I'm open to suggestions on how to improve the colour balance but I originally wrote this library to handle simple logos, although it is a lot of fun putting complex images through it :)
