### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jcubic** [patmooney/node-terminal-art#3]
What is the license of this project, is it ISC as in package.json or something else? I would be nice if there is LICENSE file and/or license info in README.

**Comment by patmooney** [comment]
Done <3

**Comment by jcubic** [comment]
FYI: license field should me mnemonic, in your case "MIT" otherwise npm will complaining when publishing, you will see if actually publish new version after change.

You also have some trash in the repo, npm will publish everything you have in directory, you need to use .npmignore so npm will skip those files.

**Comment by patmooney** [comment]
@jcubic Thanks, I was using npm's recommendation for having a license in a separate file. Have updated along with some speed improvements

https://github.com/patmooney/node-terminal-art/pull/4
